services:
  db_manager_core.engines.magento:
    autowire: true
    public: true
    class: DbManager\MagentoBundle\Processor
    arguments: []

  DbManager\MagentoBundle\Service\Platform\Magento:
    tags:
      - { name: 'app.platform' }