version: "3.7"

services:
  dbvisor-cron-server:
    build:
      context: .
      target: frankenphp_cron
    image: ${IMAGES_PREFIX:-}dbvisor-cron-server
    environment:
      APP_ENV: ${APP_ENV}
      APP_SECRET: ${APP_SECRET}
    init: true
    volumes:
      - ${PROJECT_ROOT}:/app
      - ${APP_DOCKER_PATH_DUMP}:/app/backups/backups:delegated
      - ${APP_DOCKER_PATH_CONFIG}:/app/backups/configs:delegated
      - ${APP_DOCKER_LOCAL_BACKUPS_PATH}:/app/backups/local_backups:delegated
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - dbvisor-network

volumes:
  caddy_data:
  caddy_config:

networks:
  dbvisor-network:
    name: dbvisor-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "${DBVISOR_SUBNET:-172.27.0.0/16}"