services:
  db_manager_core.engines.mysql:
    autowire: true
    public: true
    class: DbManager\MysqlBundle\Processor
    arguments: []

  db_manager_core.management.engines.mysql:
    autowire: true
    public: true
    class: DbManager\MysqlBundle\DBManagement\Management
    arguments: []
